services:
  throttlarr:
    image: ghcr.io/newandreas/throttlarr:latest
    container_name: throttlarr
    restart: unless-stopped
    # Use internal docker networking (no ports exposed) if Plex/Jellyfin/Emby are in the same network
    # ports:
    #   - "5000:5000" 
    environment:
      # qBittorrent Config
      - QB_HOST=torrent:8080 # Service name or http://IP:PORT
      - QB_USER=${QB_USER}
      - QB_PASS=${QB_PASS}

      # SABnzbd Config
      - SAB_HOST=sabnzbd:1337
      - SAB_API_KEY=${SAB_API_KEY}
      
      # Shared Speed Limits (Applies to SABnzbd and qBittorrent combined)
      - FULL_SPEED=0                # 0 = Unlimited
      - SOFT_THROTTLE_SPEED=45M     # 45M is 45 megabytes per second
      - HARD_THROTTLE_SPEED=25M
      - HARD_THROTTLE_STREAMS=3     # When three streams are detected in Tracearr it will hard throttle
      - HARD_THROTTLE_BITRATE=50000 # If a single stream exceeds this bitrate in kilobits per second it will hard throttle
      - TRACEARR_SYNC_INTERVAL=20   # How many seconds between tracearr polls and download queue adjustments

      # Tracearr Config
      - TRACEARR_URL=tracearr:3000
      - TRACEARR_TOKEN=${TRACEARR_API_KEY}
      - TRACEARR_SYNC_INTERVAL=300 # How often to poll Tracearr in seconds (default: 300, 5 minutes)
    depends_on:
      tracearr:
        condition: service_healthy
